use_frameworks!

platform :ios, '13.0'

target 'TransmedikSDK_Example' do
  pod 'TransmedikSDK', :path => '../'
  pod 'Alamofire', '~> 5.4'
  pod 'Kingfisher', '~> 5.15.8'
  pod 'FSPagerView', '~> 0.8.3'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'IQKeyboardManagerSwift', '~> 6.5.6'
  pod 'SwiftyCodeView', '~> 0.3.6'
  pod 'DropDown', '~> 2.3.13'
  pod 'MessageKit', '~>  3.0.0'
  pod 'MessageInputBar', '~>  0.4.0'
  pod 'URLEmbeddedView', '~> 0.18.0'
  pod 'SwipeCellKit', '~> 2.7.1'
  pod 'Parse', '~> 1.19.1'
  pod 'Lightbox', '~> 2.5.0'
  pod 'CDAlertView','~> 0.10.0'
  pod 'Starscream', '~> 3.1.0'
  pod 'ParseLiveQuery', '~> 2.7.0 '
#  pod 'GoogleMaps', '3.10.0'
#  pod 'GooglePlaces', '3.10.0'
  pod "ESTabBarController-swift", '~> 2.8.0 '
  pod 'MSPeekCollectionViewDelegateImplementation', '~> 3.1.1 '
  pod 'CRRefresh', '~> 1.1.3 '
  pod 'BubbleShowCase', '~> 1.2.0 '
  pod 'SVPinView', '~> 1.0'
#  pod 'ImagePickerWhatsApp', '~> 1.0.0'
  pod 'ImagePickerWhatsApp'
  pod 'DividerView', '3.0'
  pod 'YPImagePicker', '4.4.0'
  pod 'FloatRatingView', '~> 4'
  pod 'NVActivityIndicatorView', '~> 5.1.1'
  pod 'lottie-ios'
  pod 'SkeletonView', '~> 1.11.0'

  

  target 'TransmedikSDK_Tests' do
    inherit! :search_paths

    
  end
end

#pre_install do |installer|
#  installer.pod_targets.each do |pod|
#    if pod.name.eql?('NAME_OF_POD') || pod.name.start_with?('START_OF_NAME_OF_POD')
#      def pod.build_type;
#        # Uncomment one line depending on your CocoaPods version
#        Pod::BuildType.static_library # >= 1.9
#        # Pod::Target::BuildType.static_library # < 1.9
#      end
#    end
#  end
#end
